Cleanup gen9_mfc.c
This patch removes all unneeded functions/variables in gen9_mfc.c for mfc pipeline setting.

Especially it doesn't include shaders/utils/mfc_batchbuffer_avc_intra.g9b and
shaders/utils/mfc_batchbuffer_avc_inter.g9b in gen9_mfc.c because the two .g9b files are no longer
included in the package created by 'make dist'

C       i965_drv_video_la-gen9_mfc.lo
gen9_mfc.c:54:55: fatal error: shaders/utils/mfc_batchbuffer_avc_intra.g9b: No such file or directory
 #include "shaders/utils/mfc_batchbuffer_avc_intra.g9b"

Signed-off-by: Xiang, Haihao <haihao.xiang@intel.com>
Reviewed-by: Zhao Yakui <yakui.zhao@intel.com>
(cherry picked from commit 2c213d3a071c540eaba23eb2ef82db6e33327a4f)