Make the compiler happy
To avoid the error:

src/gen6_mfc_common.c:487:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^

Signed-off-by: Chih-Wei Huang <cwhuang@linux.org.tw>
(cherry picked from commit de8d3c0895ceba38bdfd11e8386e4f0d4b4dc855)