libdrm 2.4.52 is required to avoid the compiler error
  CC       i965_drv_video_la-intel_batchbuffer.lo
intel_batchbuffer.c: In function 'intel_batchbuffer_emit_reloc64':
intel_batchbuffer.c:183:24: error: 'drm_intel_bo' has no member named 'offset64'
    uint64_t offset = bo->offset64 + delta;
                        ^
make[3]: *** [i965_drv_video_la-intel_batchbuffer.lo] Error 1

Signed-off-by: Xiang, Haihao <haihao.xiang@intel.com>
Reviewed-by: Sean V Kelley <sean.v.kelley@intel.com>